/**
 * WMI (World Manufacturer Identifier) → Manufacturer name lookup.
 * First 3 chars of a VIN identify the manufacturer & country of assembly.
 */
export const WMI: Record<string, string> = {
  // ── South Africa ──────────────────────────────────────────────────────────
  AAV: "Volkswagen South Africa",
  ABM: "BMW South Africa",
  ACV: "Isuzu South Africa",
  ADB: "Mercedes-Benz South Africa",
  ADM: "GM South Africa",
  ADN: "Nissan South Africa",
  ADR: "Renault (by Nissan SA)",
  AFA: "Ford South Africa",
  AFB: "Mazda BT-50 (by Ford SA)",
  AHT: "Toyota South Africa",
  // ── Russia ────────────────────────────────────────────────────────────────
  XTA: "Lada / AvtoVAZ",
  XTC: "KAMAZ",
  XTH: "GAZ",
  XTT: "UAZ / Sollers",
  X7L: "Renault Russia / Moskvitch",
  X7M: "Hyundai / Vortex (TagAZ)",
  X4X: "BMW (Avtotor)",
  XW8: "Volkswagen Russia",
  XW7: "Toyota Russia",
  XWE: "Hyundai-Kia (Avtotor)",
  // ── Japan ─────────────────────────────────────────────────────────────────
  JAA: "Isuzu (Japan)",
  JAC: "Isuzu SUV (Japan)",
  JDA: "Daihatsu (Japan)",
  JF1: "Subaru car",
  JF2: "Subaru SUV",
  JF3: "Subaru truck",
  JF4: "Saab 9-2X (by Subaru)",
  JHA: "Hino truck",
  JHL: "Honda MPV/SUV",
  JHM: "Honda car",
  JH1: "Honda truck",
  JH2: "Honda motorcycle",
  JH4: "Acura car",
  JKA: "Kawasaki motorcycles",
  JLB: "Mitsubishi Fuso",
  JMA: "Mitsubishi (RHD Europe)",
  JMB: "Mitsubishi (LHD Europe)",
  JMF: "Mitsubishi Australia",
  JMP: "Mitsubishi (LHD)",
  JMR: "Mitsubishi (RHD)",
  JMZ: "Mazda (Europe)",
  JM0: "Mazda (Oceania)",
  JM1: "Mazda car",
  JM2: "Mazda truck",
  JM3: "Mazda SUV",
  JNA: "Nissan Diesel / UD Trucks",
  JNK: "Infiniti car",
  JNR: "Infiniti SUV",
  JN1: "Nissan car",
  JN6: "Nissan truck/van",
  JN8: "Nissan SUV",
  JP3: "Plymouth (by Mitsubishi)",
  JSA: "Suzuki (Japan)",
  JST: "Suzuki Across (by Toyota)",
  JS1: "Suzuki motorcycle",
  JS2: "Suzuki car",
  JS3: "Suzuki SUV",
  JS4: "Suzuki truck",
  JTB: "Toyota bus",
  JTD: "Toyota car",
  JTE: "Toyota SUV",
  JTF: "Toyota van/truck",
  JTH: "Lexus car",
  JTJ: "Lexus SUV",
  JTK: "Toyota car",
  JTL: "Toyota SUV",
  JTM: "Toyota SUV",
  JTN: "Toyota car",
  JTP: "Toyota SUV",
  JT1: "Toyota van",
  JT2: "Toyota car",
  JT3: "Toyota SUV",
  JT4: "Toyota truck",
  JT6: "Lexus SUV",
  JT8: "Lexus car",
  JW6: "Mitsubishi Fuso (pre-2003)",
  JYA: "Yamaha motorcycles",
  J81: "Chevrolet (by Isuzu)",
  // ── Korea ─────────────────────────────────────────────────────────────────
  KLA: "Daewoo / GM Korea (Chevrolet)",
  KLY: "Daewoo / GM Korea (Changwon)",
  KL1: "GM Korea (Chevrolet car)",
  KL4: "GM Korea (Buick)",
  KL8: "GM Korea (Chevrolet Spark)",
  KMC: "Hyundai commercial truck",
  KMH: "Hyundai car",
  KMJ: "Hyundai bus",
  KMT: "Genesis car",
  KMU: "Genesis SUV",
  KM8: "Hyundai SUV",
  KNA: "Kia car",
  KNC: "Kia truck",
  KND: "Kia SUV",
  KNE: "Kia (Europe)",
  KNM: "Renault Korea",
  KPA: "SsangYong/KGM pickup",
  KPB: "SsangYong car",
  KPT: "SsangYong/KGM SUV",
  // ── China ─────────────────────────────────────────────────────────────────
  LC0: "BYD Auto",
  LBE: "Beijing Hyundai",
  LBV: "BMW Brilliance",
  LFM: "FAW Toyota",
  LFP: "FAW Car / Bestune / Hongqi",
  LFV: "FAW-Volkswagen",
  LGB: "Dongfeng Nissan",
  LGW: "Great Wall Motor (Haval/Ora/Tank)",
  LGX: "BYD Auto (Fangchengbao)",
  LHG: "GAC Honda",
  LMG: "GAC Motor / Trumpchi",
  LNA: "GAC Aion",
  LNP: "NAC MG / Nanjing Fiat",
  LNN: "Chery / Omoda / Jaecoo",
  LNV: "Naveco (Nanjing Iveco)",
  LPS: "Polestar (China)",
  LRW: "Tesla Gigafactory Shanghai",
  LS6: "Changan / Deepal / Avatr",
  LSG: "SAIC-GM (Chevrolet/Buick/Cadillac)",
  LSJ: "SAIC MG / Roewe / IM Motors",
  LSV: "SAIC-Volkswagen",
  LVG: "GAC Toyota",
  LVH: "Dongfeng Honda",
  LVR: "Changan Mazda",
  LVS: "Changan Ford / Lincoln",
  LVT: "Chery / Exeed / Jetour",
  LVV: "Chery / Omoda / Jaecoo",
  LVY: "Volvo Cars (Daqing)",
  LW4: "Li Auto",
  LWV: "GAC Fiat Chrysler",
  LXW: "JMC Ford",
  L1N: "XPeng Motors",
  L2C: "Chery Jaguar Land Rover",
  L6T: "Geely / Lynk & Co / Zeekr",
  HES: "smart (Mercedes-Geely JV)",
  HJN: "Nio / Firefly",
  HLX: "Li Auto",
  HVW: "Volkswagen Anhui",
  HXM: "Xiaomi",
  // ── India ─────────────────────────────────────────────────────────────────
  MAB: "Mahindra & Mahindra",
  MAJ: "Ford India",
  MAK: "Honda India",
  MAL: "Hyundai India",
  MAT: "Tata Motors",
  MA1: "Mahindra",
  MA3: "Maruti Suzuki India",
  MBJ: "Toyota India",
  MBL: "Hero MotoCorp",
  MBR: "Mercedes-Benz India",
  MB8: "Suzuki Motorcycle India",
  MCA: "FCA India (Fiat/Jeep)",
  MCB: "GM India",
  ME1: "Yamaha India",
  ME3: "Royal Enfield",
  ME4: "Honda Motorcycles India",
  MZB: "Kia India",
  // ── Malaysia / Indonesia / Thailand ──────────────────────────────────────
  MHF: "Toyota Indonesia",
  MHR: "Honda Indonesia",
  MHY: "Suzuki Indonesia",
  MK2: "Mitsubishi Indonesia",
  MK3: "Wuling Indonesia (SGMW)",
  PMH: "Honda Malaysia",
  PM2: "Perodua",
  PN1: "Toyota Malaysia (UMW)",
  PN8: "Nissan Malaysia",
  PPV: "Volkswagen Malaysia",
  MMA: "Mitsubishi Thailand",
  MMS: "Suzuki Thailand",
  MNT: "Nissan Thailand",
  MR0: "Toyota Thailand",
  MR1: "Toyota Thailand",
  MR2: "Toyota Thailand (Gateway)",
  MNA: "Ford Thailand (RHD export)",
  MPA: "Isuzu Thailand",
  MPB: "Ford Thailand",
  MRH: "Honda Thailand",
  // ── UK ───────────────────────────────────────────────────────────────────
  SAA: "Austin (UK)",
  SAD: "Jaguar / Daimler (UK)",
  SAJ: "Jaguar car (UK)",
  SAL: "Land Rover (UK)",
  SAR: "Rover / MG Rover (UK)",
  SB1: "Toyota Manufacturing UK",
  SCA: "Rolls-Royce (UK)",
  SCB: "Bentley (UK)",
  SCC: "Lotus Cars (UK)",
  SCF: "Aston Martin (UK)",
  SCR: "London Electric Vehicle Company (UK)",
  SC6: "INEOS Grenadier (UK)",
  SDK: "Caterham Cars (UK)",
  SDP: "MG Motor UK",
  SED: "Vauxhall / IBC Vehicles (UK)",
  SFA: "Ford UK",
  SFD: "Alexander Dennis (UK)",
  SHH: "Honda UK car",
  SHS: "Honda UK SUV",
  SJA: "Bentley SUV (UK)",
  SJN: "Nissan Manufacturing UK",
  SKA: "Vauxhall (UK)",
  SLA: "Rolls-Royce SUV (UK)",
  SLN: "Niftylift (UK)",
  SMT: "Triumph Motorcycles (UK)",
  SMB: "McLaren (UK)",
  // ── Germany ──────────────────────────────────────────────────────────────
  WAC: "Audi / Porsche RS2",
  WAP: "Alpina",
  WAU: "Audi car",
  WA1: "Audi SUV",
  WBA: "BMW car",
  WBS: "BMW M car",
  WBX: "BMW SUV",
  WBY: "BMW i car",
  WB5: "BMW i SUV",
  WDA: "Mercedes-Benz (incomplete)",
  WDB: "Mercedes-Benz / Maybach",
  WDC: "Mercedes-Benz SUV",
  WDD: "Mercedes-Benz car",
  WDF: "Mercedes-Benz van",
  WEB: "Mercedes-Benz buses (EvoBus)",
  WEL: "e.GO Mobile",
  WF0: "Ford Germany",
  WJM: "Iveco / Iveco Magirus",
  WKE: "Krone truck trailers",
  WKK: "Setra (EvoBus)",
  WMA: "MAN Truck & Bus",
  WME: "smart",
  WMW: "MINI car",
  WMX: "Mercedes-AMG",
  WMZ: "MINI SUV",
  WP0: "Porsche car",
  WP1: "Porsche SUV",
  WUA: "Audi Sport GmbH car",
  WU1: "Audi Sport GmbH SUV",
  WVG: "Volkswagen SUV",
  WVW: "Volkswagen passenger car",
  WV1: "Volkswagen Commercial (cargo)",
  WV2: "Volkswagen Commercial (passenger)",
  WV4: "Volkswagen Commercial (Amarok T7)",
  WV5: "Volkswagen Commercial (Caravelle)",
  W0L: "Opel / Vauxhall",
  W0V: "Opel / Vauxhall (2017+)",
  W1A: "smart",
  W1K: "Mercedes-Benz car",
  W1N: "Mercedes-Benz SUV",
  W1T: "Mercedes-Benz truck",
  W1V: "Mercedes-Benz van",
  // ── France ───────────────────────────────────────────────────────────────
  VF1: "Renault",
  VF2: "Renault Trucks",
  VF3: "Peugeot",
  VF7: "Citroën",
  VF9: "French specialist",
  VGA: "Peugeot Motocycles",
  VNK: "Toyota France",
  VNV: "Nissan (by Renault France)",
  VN1: "Renault SOVAB / Opel Movano",
  VR1: "DS Automobiles",
  VR3: "Peugeot (Stellantis)",
  VR7: "Citroën (Stellantis)",
  VYS: "Renault / Alpine (Ampere)",
  // ── Spain ─────────────────────────────────────────────────────────────────
  VSS: "SEAT / Cupra",
  VSX: "Opel Spain",
  VS5: "Renault Spain",
  VS6: "Ford Spain",
  VS7: "Citroën Spain",
  VS8: "Peugeot Spain",
  VSK: "Nissan Spain",
  VWV: "Volkswagen Spain",
  // ── Belgium / Netherlands ─────────────────────────────────────────────────
  YAR: "Toyota ProAce (Belgium, by PSA)",
  YBW: "Volkswagen Belgium",
  XLA: "DAF Bus",
  XLB: "Volvo Cars (NedCar)",
  XLC: "Ford Netherlands",
  XLR: "DAF Trucks",
  XP7: "Tesla Europe (Gigafactory Berlin)",
  // ── Italy ─────────────────────────────────────────────────────────────────
  ZAC: "Jeep / Dodge Hornet (Italy)",
  ZAM: "Maserati",
  ZAP: "Piaggio / Vespa / Gilera",
  ZAR: "Alfa Romeo car",
  ZAS: "Alfa Romeo SUV",
  ZCF: "Iveco / Irisbus",
  ZDC: "Honda Italy",
  ZDM: "Ducati",
  ZFA: "Fiat",
  ZFB: "Fiat MPV/SUV",
  ZFF: "Ferrari",
  ZHW: "Lamborghini",
  ZLA: "Lancia",
  ZN6: "Maserati SUV",
  ZPB: "Lamborghini SUV",
  ZPY: "DR Automobiles",
  ZSG: "Ferrari SUV",
  // ── Sweden ───────────────────────────────────────────────────────────────
  YSC: "Cadillac BLS (by Saab)",
  YSM: "Polestar cars",
  YSP: "Volta Trucks",
  YSR: "Polestar SUV",
  YS2: "Scania (Södertälje)",
  YS3: "Saab cars",
  YV1: "Volvo Cars",
  YV2: "Volvo Trucks",
  YV3: "Volvo Buses",
  YV4: "Volvo SUV",
  // ── Czech / Slovakia / Hungary ────────────────────────────────────────────
  TMA: "Hyundai Czech",
  TMB: "Škoda",
  TMC: "Hyundai Czech SUV",
  TSM: "Suzuki Hungary",
  U5Y: "Kia Slovakia",
  U6Y: "Kia Slovakia",
  // ── Turkey ────────────────────────────────────────────────────────────────
  NMT: "Toyota Turkey",
  NM0: "Ford Turkey (Ford Otosan)",
  NM1: "Renault Turkey",
  NM4: "Fiat Turkey (Tofaş)",
  NLH: "Hyundai Turkey",
  NL1: "TOGG (Turkey)",
  // ── Opel / Vauxhall (assembled in various countries) ─────────────────────
  VXK: "Opel/Vauxhall car/SUV (France)",
  VXE: "Opel/Vauxhall van (France)",
  VXF: "Fiat van (France)",
  // ── USA ──────────────────────────────────────────────────────────────────
  "1FA": "Ford car (USA)",
  "1FB": "Ford bus/van (USA)",
  "1FM": "Ford SUV (USA)",
  "1FT": "Ford truck (USA)",
  "1FU": "Freightliner truck (USA)",
  "1G1": "Chevrolet car (USA)",
  "1G6": "Cadillac car (USA)",
  "1GC": "Chevrolet truck (USA)",
  "1GK": "GMC SUV (USA)",
  "1GN": "Chevrolet SUV (USA)",
  "1GT": "GMC truck (USA)",
  "1GY": "Cadillac SUV (USA)",
  "1HD": "Harley-Davidson",
  "1HG": "Honda (Ohio, USA)",
  "1JJ": "Wabash trailer (USA)",
  "1N4": "Nissan car (USA)",
  "1N6": "Nissan truck (USA)",
  "1NX": "Toyota (NUMMI, USA)",
  "1VW": "Volkswagen car (USA)",
  "1XK": "Kenworth truck (USA)",
  "1XP": "Peterbilt truck (USA)",
  "1YV": "Mazda (AutoAlliance, USA)",
  "5FN": "Honda (Alabama, USA)",
  "5J6": "Honda SUV (Ohio, USA)",
  "5J8": "Acura SUV (Ohio, USA)",
  "5N1": "Nissan/Infiniti SUV (USA)",
  "5NM": "Hyundai (Alabama, USA)",
  "5NP": "Hyundai car (Alabama, USA)",
  "5TD": "Toyota SUV (Indiana, USA)",
  "5TF": "Toyota truck (Texas, USA)",
  "5UX": "BMW SUV (USA)",
  "5XX": "Kia car (Georgia, USA)",
  "5XY": "Kia/Hyundai SUV (Georgia, USA)",
  "5YJ": "Tesla Model S/3 (USA)",
  "7FC": "Rivian truck (USA)",
  "7PD": "Rivian SUV (USA)",
  "7SA": "Tesla Model X/Y (USA)",
  "7G2": "Tesla Semi/Cybertruck (USA)",
  "4T1": "Toyota (Kentucky, USA)",
  "4T3": "Toyota SUV (Kentucky, USA)",
  "4US": "BMW car (USA)",
  "4S3": "Subaru car (USA)",
  "4S4": "Subaru SUV/MPV (USA)",
  // ── Canada ────────────────────────────────────────────────────────────────
  "2HG": "Honda (Canada)",
  "2HK": "Honda SUV (Canada)",
  "2T1": "Toyota (TMMC, Canada)",
  "2T3": "Toyota SUV (TMMC, Canada)",
  // ── Mexico ────────────────────────────────────────────────────────────────
  "3CZ": "Honda (Mexico)",
  "3FA": "Ford (Mexico)",
  "3FM": "Ford SUV (Mexico)",
  "3FT": "Ford truck (Mexico)",
  "3G1": "Chevrolet (Mexico)",
  "3GC": "Chevrolet truck (Mexico)",
  "3HG": "Honda car (Mexico)",
  "3MZ": "Mazda (Mexico)",
  "3MV": "Mazda SUV (Mexico)",
  "3N1": "Nissan (Mexico)",
  "3VW": "Volkswagen (Mexico)",
  "3VV": "Volkswagen SUV (Mexico)",
  "3MY": "Toyota (by Mazda Mexico)",
  // ── Brazil ────────────────────────────────────────────────────────────────
  "9BD": "Fiat Brazil",
  "9BF": "Ford Brazil",
  "9BG": "Chevrolet Brazil",
  "9BM": "Mercedes-Benz Brazil",
  "9BR": "Toyota Brazil",
  "9BW": "Volkswagen Brazil",
  "93H": "Honda Brazil",
  "93Y": "Renault Brazil",
  "95P": "Hyundai / Chery Brazil",
  "98M": "BMW Brazil",
  // ── Australia ─────────────────────────────────────────────────────────────
  "6FP": "Ford Australia",
  "6G1": "Holden / GM Australia",
  "6MM": "Mitsubishi Australia",
  "6T1": "Toyota Australia",
  // ── New Zealand ───────────────────────────────────────────────────────────
  "7A3": "Honda New Zealand",
  "7A4": "Toyota New Zealand",
  "7A5": "Ford New Zealand",
  "7A7": "Nissan New Zealand",
  "7A1": "Mitsubishi New Zealand",
  "7JD": "Volvo Cars SUV",
  "7JR": "Volvo Cars",
};

export function lookupWmi(wmi: string): string {
  if (!wmi) return "";
  // Try exact match first, then first 3 chars
  return WMI[wmi] ?? WMI[wmi.slice(0, 3)] ?? "";
}
